export const PageAnimation = {
    hidden:{
        opacity:0,
        y:100
    },
    show:{
        opacity:1,
        y:0,
        transition:{
            duration:.7,
            ease:"easeOut"
        }
    },
    exit:{
        opacity:0,
        y:100,
        transition:{
            duration:.4,
            ease:"easeOut"
        }
    }
}